version: '3.7'

services:
  archivedb:
    image: intersystemsdc/irisdemo-demo-iotpredmaint:archivedb-version-1.0.0
    init: true
    hostname: archivedb
    restart: on-failure

    ports:
    # 51773 is the superserver default port
    - "9093:51773"
    # 52773 is the webserver/management portal port
    - "9092:52773"
    volumes:
     - ./common_shared:/tmp/common_shared   # The production will be looking into this folder for new PMML files
                                       # that will be sent by the advancedanalytics service.
  iotmon:
    depends_on:
    - archivedb
    build: 
      context: ./iotmon
    image: intersystemsdc/irisdemo-demo-iotpredmaint:iotmon-version-1.0.0
    init: true
    hostname: iotmon
    restart: on-failure

    ports:
    # 51773 is the superserver default port
    - "9095:51773"
    # 52773 is the webserver/management portal port
    - "9094:52773"
    volumes:
     - ./common_shared:/tmp/common_shared   # The production will be looking into this folder for new PMML files
                                       # that will be sent by the archivedb service. Of course we would
                                       # never receive files from archivedb on the real world. But on this
                                       # demo, we are.
      
  sparkmaster:
    image: intersystemsdc/irisdemo-base-spark-iris:${SPARK_IMAGE_VERSION}
    hostname: sparkmaster # Must be always sparkmaster
    depends_on:
    - iotmon
    init: true
    environment:
      SPARK_NODE_TYPE: Master
      SPARK_PUBLIC_DNS: localhost
      IRIS_MASTER_HOST: archivedb # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./common_shared:/tmp/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
                                       # that will be sent by the advancedanalytics service.

  worker1:
    depends_on:
    - sparkmaster
    init: true
    image: intersystemsdc/irisdemo-base-spark-iris:${SPARK_IMAGE_VERSION}
    hostname: worker1

    environment:
      IRIS_MASTER_HOST: archivedb # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - sparkmaster
    ports:
      - 8081:8081
    volumes:
      - ./common_shared:/tmp/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
                                       # that will be sent by the advancedanalytics service.
  worker2:
    depends_on:
    - sparkmaster
    init: true
    image: intersystemsdc/irisdemo-base-spark-iris:${SPARK_IMAGE_VERSION}
    hostname: worker2

    environment:
      IRIS_MASTER_HOST: archivedb # DNS based on the name of the service!
      IRIS_MASTER_PORT: 51773 
      IRIS_MASTER_USERNAME: SuperUser 
      IRIS_MASTER_PASSWORD: sys 
      IRIS_MASTER_NAMESPACE: APP 

      SPARK_NODE_TYPE: Worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - sparkmaster
    ports:
      - 8082:8081
    volumes:
      - ./common_shared:/tmp/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
                                       # that will be sent by the advancedanalytics service.

  advancedanalytics:
    image: intersystemsdc/irisdemo-base-zeppelin:${ZEPPELIN_IMAGE_VERSION}
    init: true
    ports:
    - "9096:9090"   # Zeppelin
    - 4141:4040     # Zeppelin Spark UI
    volumes:
     - ./common_shared:/tmp/common_shared   # Shared between all spark nodes. Good place to place a file we are working with.
                                     # that will be sent by the advancedanalytics service.
     - type: bind
       source: ./advanced_analytics/shared/
       target: /shared

    environment:
    - IRIS_MASTER_HOST=archivedb # DNS based on the name of the service!
    - IRIS_MASTER_PORT=51773 
    - IRIS_MASTER_USERNAME=SuperUser 
    - IRIS_MASTER_PASSWORD=sys 
    - IRIS_MASTER_NAMESPACE=APP 
  
