#!/bin/bash

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

git submodule update --init --recursive

source ./buildtools.sh

# Images that must be pushed after build
rm -f ./images_built

#
# Build IOTMON image
#
IOTMON_IMAGE_NAME=intersystemsdc/$GIT_REPO_NAME:iris-${DOCKER_TAG}
docker build -t $IMAGE_NAME ./iotmon
exit_if_error "IOTMON Image could not be built"

echo $IOTMON_IMAGE_NAME >> ../images_built

#
# Build ARCHIVEDB image
#
ARCHIVEDB_IMAGE_NAME=intersystemsdc/$GIT_REPO_NAME:iris-${DOCKER_TAG}
docker build -t $IMAGE_NAME ./archivedb
exit_if_error "ARCHIVEDB Image could not be built"

echo $ARCHIVEDB_IMAGE_NAME >> ../images_built
